### ISSUE TITLE
Allow mounting inside github workspace

### ISSUE THREAD

**Issue by samypr100** [samypr100/setup-dev-drive#6]
Possible new input option `mount-path`. Explore using `Add-PartitionAccessPath` to see if it yields satisfactory results.

**Comment by samypr100** [comment]
> Mounted folders are supported only on NTFS-formatted partitions.

[Only supported by NTFS at this time](https://learn.microsoft.com/en-us/powershell/module/storage/add-partitionaccesspath?view=windowsserver2022-ps#notes), closing for the time being.

**Comment by malkia** [comment]
I'm able to use mounted folder with ReFS too - I keep changing between NTFS and ReFS here, trying out whether I can use dedup before compressing the cache file (I can't yet, or I'm missing some stuff on the windows server 2022 dc github vm), but I'm mounting the d:\d.vhdx file into d:\d folder (and then using this for the bazel disk cache)

Here this run - https://github.com/malkia/opentelemetry-cpp/actions/runs/9237167781/job/25413807799 under "mount cache disk" - Here I'm setting the mount point - https://github.com/malkia/opentelemetry-cpp/blob/a3ef324f262507fd6244e911878d960c28eb9280/.github/workflows/otel_sdk.yml#L47C38-L47C42 and then it works

The mount value is stored in the registry, so when the VM is re-created it's lost - e.g. it's not property of the .VHDX file itself (or at least my findings led me to believe os, but could be wrong there).

Hence I recreate the access-path. Granted, this might fail if the machine is not clean (and reused) - if you have such scenario, but with the current github hosted vms I don't expect this to be the case.

Hope that helps, and looking towards using this action!
